const fs=require('fs'),path=require('path'),{execFileSync}=require('child_process');
const webDir=path.resolve(process.argv[2]),jobDir=path.resolve(process.argv[3]);
const androidDir=path.join(jobDir,'android');fs.mkdirSync(path.join(androidDir,'app','src','main','assets'),{recursive:true});
function write(p,s){fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,s)}
fs.cpSync(webDir,path.join(androidDir,'app','src','main','assets','www'),{recursive:true});
write(path.join(androidDir,'settings.gradle'),'pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }\ndependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories{google();mavenCentral()} }\nrootProject.name="ZipToApk"\ninclude ":app"\n');
write(path.join(androidDir,'build.gradle'),'plugins { id "com.android.application" version "8.7.3" apply false }\n');
write(path.join(androidDir,'app','build.gradle'),'plugins { id "com.android.application" }\n\nandroid { namespace "com.lanzy.ziptoapk"; compileSdk 35\n defaultConfig { applicationId "com.lanzy.ziptoapk"; minSdk 23; targetSdk 35; versionCode 1; versionName "1.0" } }\n\ndependencies { implementation "androidx.appcompat:appcompat:1.7.0" }\n');
write(path.join(androidDir,'app','src','main','AndroidManifest.xml'),'<?xml version="1.0" encoding="utf-8"?><manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:theme="@style/AppTheme" android:label="ZIP to APK"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity></application></manifest>');
write(path.join(androidDir,'app','src','main','res','values','styles.xml'),'<resources><style name="AppTheme" parent="android:style/Theme.Material.Light.NoActionBar"><item name="android:fontFamily">sans</item><item name="android:colorAccent">#171717</item></style></resources>');
write(path.join(androidDir,'app','src','main','java','com','lanzy','ziptoapk','MainActivity.java'),'package com.lanzy.ziptoapk;\nimport android.app.*;import android.os.*;import android.webkit.*;import android.view.*;\npublic class MainActivity extends Activity{public void onCreate(Bundle b){super.onCreate(b);WebView w=new WebView(this);w.setWebViewClient(new WebViewClient());w.getSettings().setJavaScriptEnabled(true);w.getSettings().setDomStorageEnabled(true);w.loadUrl("file:///android_asset/www/index.html");setContentView(w);}}');
try{execFileSync(process.env.GRADLE||'gradle',['-p',androidDir,'assembleRelease'],{stdio:'inherit'});fs.copyFileSync(path.join(androidDir,'app','build','outputs','apk','release','app-release.apk'),path.join(jobDir,'app-release.apk'))}catch(e){process.exit(1)}
