import crypto from 'node:crypto';
const OWNER='ikyikiy62-pixel',REPO='cekcekz-inilanzy',WORKFLOW='build-apk.yml',REF='feat/vercel-ready';
export const config={api:{bodyParser:false}};
async function body(req){const a=[];for await(const c of req)a.push(c);return Buffer.concat(a)}
function multipart(buf,ct){const m=ct.match(/boundary=(?:"([^"]+)"|([^;]+))/i);if(!m)throw Error('Invalid multipart form.');const b=Buffer.from('--'+(m[1]||m[2])),out=[];let s=0;for(;;){const i=buf.indexOf(b,s);if(i<0)break;const n=buf.indexOf(b,i+b.length);if(n<0)break;const p=buf.subarray(i+b.length+2,n-2),x=p.indexOf(Buffer.from('\r\n\r\n'));if(x<0){s=n;continue}const h=p.subarray(0,x).toString(),d=p.subarray(x+4),name=/name="([^"]+)"/i.exec(h)?.[1];if(name)out.push({name,data:d});s=n}return out}
async function gh(p,opt={}){const t=process.env.GITHUB_TOKEN;if(!t)throw Error('GITHUB_TOKEN belum diatur di Vercel.');const r=await fetch('https://api.github.com'+p,{...opt,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${t}`,'X-GitHub-Api-Version':'2022-11-28',...(opt.headers||{})}});const txt=await r.text();if(!r.ok)throw Error(`GitHub API ${r.status}: ${txt.slice(0,300)}`);return txt?JSON.parse(txt):null}
async function upload(url,data,name,type){const u=new URL(url);u.searchParams.set('name',name);const t=process.env.GITHUB_TOKEN,r=await fetch(u,{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':type,Accept:'application/vnd.github+json'},body:data});if(!r.ok)throw Error(`Upload ${name} failed: ${r.status}`);return r.json()}
function cleanName(v){return String(v||'Lanzy App').replace(/[<>"&]/g,'').trim().slice(0,40)||'Lanzy App'}
function progressFromJob(job,run){if(!job?.steps)return run.status==='queued'?5:20;const done=job.steps.filter(s=>s.status==='completed').length,total=job.steps.length||1;return Math.max(5,Math.min(99,Math.round((done/total)*100)))}
export default async function handler(req,res){try{
 if(req.method==='GET'){const id=String(req.query?.id||'');if(!/^builder-[\w-]+$/.test(id))return res.status(400).json({error:'Invalid build id'});let rel;try{rel=await gh(`/repos/${OWNER}/${REPO}/releases/tags/${encodeURIComponent(id)}`)}catch(e){return res.status(200).json({id,status:'queued',success:false,progress:3,logs:['Menunggu server build…']})}const apk=rel.assets?.find(a=>/\.apk$/i.test(a.name));if(apk)return res.status(200).json({id,status:'completed',success:true,progress:100,download:apk.browser_download_url,logs:['✓ Build APK selesai.','✓ APK siap diunduh.']});const runs=await gh(`/repos/${OWNER}/${REPO}/actions/runs?event=workflow_dispatch&branch=${encodeURIComponent(REF)}&per_page=50`);const run=runs.workflow_runs?.filter(r=>r.created_at>=rel.created_at).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0];if(!run)return res.status(200).json({id,status:'queued',success:false,progress:8,logs:['• Menunggu GitHub Actions…']});const jobs=await gh(`/repos/${OWNER}/${REPO}/actions/runs/${run.id}/jobs?per_page=20`);const job=jobs.jobs?.[0];const logs=[];if(job?.steps)for(const s of job.steps)logs.push(`${s.status==='completed'?(s.conclusion==='success'?'✓':'✕'):'•'} ${s.name}`);if(run.status==='completed'&&run.conclusion!=='success')return res.status(200).json({id,status:'failed',success:false,progress:100,logs:[...logs,'✕ Build APK gagal.']});return res.status(200).json({id,status:run.status==='in_progress'?'building':'queued',success:false,progress:progressFromJob(job,run),logs});}
 if(req.method!=='POST')return res.status(405).json({error:'POST only'});const p=multipart(await body(req),req.headers['content-type']||''),zip=p.find(x=>x.name==='zip'),icon=p.find(x=>x.name==='icon'),namePart=p.find(x=>x.name==='appName');if(!zip||!icon)return res.status(400).json({error:'ZIP dan icon wajib dipilih.'});if(zip.data.length>50*1024*1024)return res.status(413).json({error:'ZIP maksimal 50 MB.'});if(icon.data.length>10*1024*1024)return res.status(413).json({error:'Icon maksimal 10 MB.'});const appName=cleanName(namePart?.data?.toString()),id=`builder-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`;const release=await gh(`/repos/${OWNER}/${REPO}/releases`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tag_name:id,name:`Builder ${id}`,draft:false,prerelease:true})});const za=await upload(release.upload_url.replace('{?name,label}',''),zip.data,`site-${id}.zip`,'application/zip');const ia=await upload(release.upload_url.replace('{?name,label}',''),icon.data,`icon-${id}.img`,'application/octet-stream');await gh(`/repos/${OWNER}/${REPO}/actions/workflows/${WORKFLOW}/dispatches`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:REF,inputs:{zip_url:za.browser_download_url,icon_url:ia.browser_download_url,release_tag:id,app_name:appName}})});return res.status(202).json({ok:true,id,status:'queued',progress:3});
 }catch(e){return res.status(500).json({error:e.message||'Build gagal.'})}}
