import crypto from 'node:crypto';
const OWNER='ikyikiy62-pixel', REPO='cekcekz-inilanzy', WORKFLOW='build-apk.yml', REF='feat/vercel-ready';
export const config={api:{bodyParser:false}};
async function body(req){const a=[];for await(const c of req)a.push(c);return Buffer.concat(a)}
function multipart(buf,ct){const m=ct.match(/boundary=(?:"([^"]+)"|([^;]+))/i);if(!m)throw Error('Invalid multipart form.');const b=Buffer.from('--'+(m[1]||m[2])),out=[];let s=0;for(;;){const i=buf.indexOf(b,s);if(i<0)break;const n=buf.indexOf(b,i+b.length);if(n<0)break;const p=buf.subarray(i+b.length+2,n-2),x=p.indexOf(Buffer.from('\r\n\r\n'));if(x<0){s=n;continue}const h=p.subarray(0,x).toString(),d=p.subarray(x+4),name=/name="([^"]+)"/i.exec(h)?.[1];if(name)out.push({name,data:d});s=n}return out}
async function gh(path,opt={}){const t=process.env.GITHUB_TOKEN;if(!t)throw Error('GITHUB_TOKEN belum diatur di Vercel.');const r=await fetch('https://api.github.com'+path,{...opt,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${t}`,'X-GitHub-Api-Version':'2026-03-10',...(opt.headers||{})}});const txt=await r.text();if(!r.ok)throw Error(`GitHub API ${r.status}: ${txt.slice(0,300)}`);return txt?JSON.parse(txt):null}
async function upload(url,data,name,type){const u=new URL(url);u.searchParams.set('name',name);const t=process.env.GITHUB_TOKEN,r=await fetch(u,{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':type,Accept:'application/vnd.github+json'},body:data});if(!r.ok)throw Error(`Upload ${name} failed: ${r.status}`);return r.json()}
export default async function handler(req,res){try{
 if(req.method==='GET'){const id=String(req.query?.id||'');if(!/^builder-[\w-]+$/.test(id))return res.status(400).json({error:'Invalid build id'});const rel=await gh(`/repos/${OWNER}/${REPO}/releases/tags/${encodeURIComponent(id)}`);const apk=rel.assets?.find(a=>a.name==='app-release.apk');if(apk)return res.status(200).json({status:'complete',download:apk.browser_download_url});const runs=await gh(`/repos/${OWNER}/${REPO}/actions/runs?event=workflow_dispatch&per_page=20`);const run=runs.workflow_runs?.find(r=>r.head_branch===REF&&r.created_at>=rel.created_at);return res.status(200).json({status:run?.status==='completed'?(run.conclusion==='success'?'complete':'failed'):'building'});}
 if(req.method!=='POST')return res.status(405).json({error:'POST only'});const p=multipart(await body(req),req.headers['content-type']||''),zip=p.find(x=>x.name==='zip'),icon=p.find(x=>x.name==='icon');if(!zip||!icon)return res.status(400).json({error:'ZIP dan icon wajib dipilih.'});if(zip.data.length>50*1024*1024)return res.status(413).json({error:'ZIP maksimal 50 MB.'});if(icon.data.length>10*1024*1024)return res.status(413).json({error:'Icon maksimal 10 MB.'});const id=`builder-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`;const release=await gh(`/repos/${OWNER}/${REPO}/releases`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tag_name:id,name:`Builder ${id}`,draft:false,prerelease:true})});const za=await upload(release.upload_url.replace('{?name,label}',''),zip.data,`site-${id}.zip`,'application/zip');const ia=await upload(release.upload_url.replace('{?name,label}',''),icon.data,`icon-${id}.img`,'application/octet-stream');await gh(`/repos/${OWNER}/${REPO}/actions/workflows/${WORKFLOW}/dispatches`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:REF,inputs:{zip_url:za.browser_download_url,icon_url:ia.browser_download_url,release_tag:id}})});return res.status(202).json({ok:true,id,status:'building'});
 }catch(e){return res.status(500).json({error:e.message||'Build gagal.'})}}
